base/urls.py
from django.urls import path, include
from .views import  TaskList, TaskDetail, TaskCreate, TaskUpdate, DeleteView
from .views import CustomLoginview, RegisterPage, ProfilePage

from django.contrib.auth.views import LogoutView
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('login/', CustomLoginview.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='login'), name='logout'),
    path('register/', RegisterPage.as_view(), name='register'),
    path('profile/', ProfilePage.as_view(), name='profile'),


    path('', TaskList.as_view(), name='tasks'),
    path('task/<int:pk>/', TaskDetail.as_view(), name='task'),
    path('task-create/', TaskCreate.as_view(), name='task-create'),
    path('task-update/<int:pk>/', TaskUpdate.as_view(), name='task-update'),
    path('task-delete/<int:pk>/', DeleteView.as_view(), name='task-delete'),
    

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todo_list/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path ('', include('base.urls')),
    path('oauth/', include('social_django.urls', namespace='social')), 
]

base/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
from django.db.models.deletion import CASCADE
from django.utils import timezone

# Create your models here.

TIPOS_TASKS = (
    ('Pessoal', ("Pessoal")),
    ('Profissional', ("Profissional")),
    ('Outros', ("Outros"))
       
)

class Task(models.Model):
    user            = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    title           = models.CharField(max_length=200)
    description     = models.TextField(null=True, blank=True)
    complete        = models.BooleanField(default=False)
    create          = models.DateTimeField(auto_now_add=True)
    date            = models.DateTimeField(auto_now_add=True, blank=True)
    tipo            = models.CharField(max_length=50, choices=TIPOS_TASKS, default="Profissional")
    

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics') 
         
    def __str__(self):
        return f'{self.user.username} Profile'
    
    def save (self):
        super().save()
            

     
            
        

    
    
    
def __str__(self):
    return self.title

class Meta:
    ordering = ['complete']
    

base/forms.py
from django import forms
from .models import *

from django.contrib.auth.models import User
from .models import Profile


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = [ 'title', 'description', 'tipo', 'complete'] 

        widgets = {
            'title':forms.TextInput(attrs={'class':'form-control', 'placeholder':'Título da Tarefa'}),
            'description':forms.Textarea(attrs={'cols':20, 'rows': 6, 'class':'form-control', 'placeholder':'Sobre a sua tarefa...' }),
            'complete':forms.CheckboxInput(attrs={'class':'form-control', 'class':'mail-choice', 'type': 'checkbox', 'name':'msg', 'for':'mail30' }),
                
            }
        labels = {
            'title': 'Título',
            'description': 'Descrição',
            'complete': 'Status da tarefa'
        }


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()
    
    class Meta:
        model = User
        fields = ['username', 'email']
        
class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']
        

base/views.py
from django.http.response import HttpResponse
from django.shortcuts import redirect, render
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView
from django.urls import reverse_lazy

from django.contrib.auth.views import LoginView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login

from django.views.generic import TemplateView


from .models import Task, Profile
from .forms import TaskForm, UserUpdateForm, ProfileUpdateForm

# Aqui comeca o pagode... 

# def ProfilePage(request):
#     return render(request, 'base/profile.html')

class ProfilePage(LoginRequiredMixin, TemplateView) :
      template_name = "base/profile.html" 
      
      def profile(request):
        if request.method == 'POST':
            u_form = UserUpdateForm(instance=request.user)
            p_form = ProfileUpdateForm(instance=request.user.profile)
     
    
        context = {
            'u_form' : u_form,
            'p_form' : p_form
    }
        return render(request, 'base/profile.html', context)

class HomeView(LoginRequiredMixin, TemplateView):
    template_name = "home.html" 


class CustomLoginview(LoginView):
    template_name = 'base/login.html'
    fields = '__all__'
    redirect_authenticated_user = True

    def  get_success_url(self):
        return reverse_lazy ('tasks')
    
class RegisterPage(FormView):
    template_name = 'base/register.html'
    form_class = UserCreationForm
    fields = ['first_name', 'last_name', 'username', 'email', 'password1', 'password2']
    redirect_authenticated_user = True
    success_url = reverse_lazy('tasks')

    def form_valid(self, form):
        user = form.save()
        if user is not None:
            login(self.request, user)
        return super(RegisterPage, self).form_valid(form)

    def get(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect('tasks')
        return super (RegisterPage, self).get(*args, **kwargs)

    


class TaskList(LoginRequiredMixin, ListView):
    model = Task
    context_object_name = 'tasks'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context ['tasks'] = context['tasks'].filter(user=self.request.user)
        context ['counttotal'] = context['tasks'].count()
        context ['count'] = context['tasks'].filter(complete=False).count()
        context ['countcomplete'] = context['tasks'].filter(complete=True).count()
        context ['complete'] = context['tasks'].filter(complete=True)
        
        search_input = self.request.GET.get('search-area') or ''
        if search_input:
            context['tasks'] = context['tasks'].filter(
                title__icontains=search_input)    

        context['search_input'] = search_input      
        return context

class TaskDetail(LoginRequiredMixin, DetailView):
    model = Task
    context_object_name = 'task'
    template_name = 'base/task.html'
    def get_context_data(self, **kwargs):
            context = super().get_context_data(**kwargs)
            
            return context

class TaskCreate(LoginRequiredMixin, CreateView):
    model = Task
    form_class = TaskForm

    # fields = '__all__'
    #fields = ['title', 'description', 'complete', 'date']
    

    success_url = reverse_lazy('tasks')
    
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(TaskCreate, self).form_valid(form)

class TaskUpdate(LoginRequiredMixin, UpdateView):
    model = Task
    #fields = '__all__'
    form_class = TaskForm
    success_url = reverse_lazy('tasks')

class DeleteView(LoginRequiredMixin, DeleteView):
    model = Task
    context_object_name = 'task'
    success_url = reverse_lazy('tasks')

base/templates/base/profile.html
{% extends 'base/task_list.html' %}
{% load crispy_forms_tags %}
{%load static %}

{% block content %}



{% comment %} <div class="mail-detail">
     <div class="mail-detail-header">
      <div class="mail-detail-profile">

<div class="content-section">
     <div class="media">
          <img class="rounded-circle account-img" src="{{user.profile.image.url}}">
          <div class="media-body">
               <h2 class="account-heading"> {{user.username}} </h2>
               <p class="text-secondary"> {{user.email}} </p>
          </div>
     </div>
<hr>
<form method="POST" enctype="multipart/form-data">
     {% csrf_token %}
     <fieldset class = "form-group"> 
          <legend class = "border-bottom mb-4"> Join </legend>


          {{form|crispy}}
          {{ u_form|crispy }}
          {{ p_form|crispy }}

     </fieldset>
<div class="form-group">
     <input type="submit" value="Salvar" class="add-button" name="action">          
</div>
</form> {% endcomment %}
<div class="content-section">
     <div class="media"> 
               <div class="row">
                    <div class="small-7 medium-5 large-4 column end small-centered card">
                    <div class="card-top"><a href="#0">
                         <div class="overlay">
                         <h1>Minhas Informações</h1>
                         </div></a><img class="card-img" src="{{user.profile.image.url}}"/> </div>
                    <div class="triangle">
                    <div class="circle-button" id="circleDrop">
                         <img class="close" src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/324479/close.svg"/></div>
                    </div>
                    <div class="card-middle">
                    <h5 class="more"> <b> Meu Usuário:</b> {{user.username}} <p> <b> Meu E-mail: </b {{user.email}} </h5>

                    </div>

                    
                    <div class="card-bottom text-center">
                    <h2 class="card-title"> </h2>
                    </div>
                    <div class="mail-textarea">
                         <div class="textarea-icons">
                            <div class="send">
                            <a class="add-button" href="{% url 'tasks' %}"> 
                           <i class="fas fa-arrow-left fa-2x"> <big>  </big> </i>
                           </a>
                           
                            </div>     
                            </div>
                          
                            </div>
                    </div>
                    
               </div>
               
               <!-- partial -->
                    <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
                    <script  src="{%static 'script-profile.js'%}"></script>
               

{%endblock%}

base/templates/base/task.html
{% extends 'base/task_list.html' %}


 {% block content %}


 
   <div class="mail-detail">
    <div class="mail-detail-header">
     <div class="mail-detail-profile">
      <img src="{{user.profile.image.url}}" alt="" class="members inbox-detail" />
      <div class="mail-detail-name">Olá,   <b style="text-transform: capitalize"/>   {{user.username}}. </b> <p> <small> Veja aqui a sua TAREFA criada: </small> </b> </div>
     </div>
    
     <div class="mail-icons">
     
  
         <a href="{% url 'task-delete' task.id %}"> 
       <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-trash-2">
         <path d="M3 6h18M19 6v14a2 2 0 01-2 2H7a2 2 0 01-2-2V6m3 0V4a2 2 0 012-2h4a2 2 0 012 2v2M10 11v6M14 11v6" /></svg>
       </a>
       <a href="{% url 'task-update' task.id %}"> 
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-check-square">
    
       <path d="M9 11l3 3L22 4" />
       <path d="M21 12v7a2 2 0 01-2 2H5a2 2 0 01-2-2V5a2 2 0 012-2h11" /></svg>
       </a>
     </div>
    </div>
 

    <div class="mail-contents">
     <div class="mail-contents-subject">

          {% if task.complete %}
            <input type="checkbox" name="msg" id="mail20" class="mail-choice" checked>
          {%else%}
            <input type="checkbox" name="msg" id="mail20" class="mail-choice" >
          {%endif%}
       
      <label for="mail20"></label>
      <div class="mail-contents-title">  <i class="fas fa-arrow-circle-right"></i> <big> {{task.title}} </big> </div>
     </div>
     <div class="mail">
      <div class="mail-time">
       <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-clock">
        <circle cx="12" cy="12" r="10" />
        <path d="M12 6v6l4 2" /></svg>
       {{task.date}}
      </div>


  
      <div class="mail-checklist">
      {% if task.complete %}
       <input type="checkbox" name="msg" id="mail30" class="mail-choice" checked>
       <label for="mail30"> Tarefa concluída.</label>
      
      {%else%}

  <input type="checkbox" name="msg" id="mail30" class="mail-choice" >
       <label for="mail30"> Tarefa não concluída.</label>
    {%endif%}
       </div>
      
      <div class="mail-doc">
       <div class="mail-doc-wrapper">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file-text">
         <path d="M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8z" />
         <path d="M14 2v6h6M16 13H8M16 17H8M10 9H8" /></svg>
        <div class="mail-doc-detail">
         <div class="mail-doc-name"> <b>  </b> <big>  {{task.tipo}} </big> </div>
        </div>
       </div>
       <div class="mail-doc-icons">
       <a href="{% url 'task-delete' task.id %}"> 
       <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-trash-2">
         <path d="M3 6h18M19 6v14a2 2 0 01-2 2H7a2 2 0 01-2-2V6m3 0V4a2 2 0 012-2h4a2 2 0 012 2v2M10 11v6M14 11v6" /></svg>
       </a>
       <a href="{% url 'task-update' task.id %}"> 
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-check-square">
    
       <path d="M9 11l3 3L22 4" />
       <path d="M21 12v7a2 2 0 01-2 2H5a2 2 0 01-2-2V5a2 2 0 012-2h11" /></svg>
       </a>
       </div>
       </div>
     </div>
    </div>
    
    <div class="mail-textarea">
   <div class="textarea-icons">
      <div class="send">
      <a class="add-button" href="{% url 'tasks' %}"> 
     <i class="fas fa-arrow-left"> <big> Voltar </big> </i>
     </a>
     
      </div>     
      </div>
    
      </div>
    </div></div></div>

 {% endblock content %}

base/templates/base/task_confirm_delete.html
{% extends 'base/task_list.html' %}

{% block content %}

{% comment %} <a href="{% url 'tasks' %}"> Voltar </a>
<form method="POST">
{% csrf_token%}
<p> Tem certeza que irá deletar a tarefa "{{task.title}}" ? </p>
<input type="submit" value="Sim Deletar " />
<a href="{% url 'tasks' %}"> Não Voltar </a>

</form> {% endcomment %}


  <div id="error-box">
    
    <div class="dot two"></div>
    <div class="face2">
      <div class="eye"></div>
      <div class="eye right"></div>
      <div class="mouth sad"></div>
    </div>
    <div class="shadow move"></div>
    <form method="POST">
    {% csrf_token%}

    <button class="button-box">
        <h1 class="red">Excluir</h1></button>

    </form>
</div>
  <div id="success-box">
    <div class="dot"></div>
    <div class="dot two"></div>
    <div class="face">
      <div class="eye"></div>
      <div class="eye right"></div>
      <div class="mouth happy"></div>
    </div>
    <div class="shadow scale"></div>
    <button class="button-box" name="button" type="submit" onclick="location.href='{% url "tasks" %}'">
        <h1 class="green"> Cancelar </h1></button>

  </div>
  </div>
</div>



{%endblock%}

base/templates/base/task_form.html
{% extends 'base/task_list.html' %}
{% block content %}
{% load crispy_forms_tags %}

   <div class="mail-detail">
    <div class="mail-detail-header">
     <div class="mail-detail-profile">
      <img src="{{user.profile.image.url}}" alt="" class="members inbox-detail" />
      <div class="mail-detail-name">Olá,  <b style="text-transform: capitalize" />  
          {{user.username}}. </b>
           <br>Crie sua tarefa aqui.</div>
     </div> </div> </div>


{% comment %} <a href="{% url 'tasks' %}"> Voltar </a> {% endcomment %}

     <form  method="POST"  >
    {% csrf_token %}
      <div class="form-row">
    <div class="col">
    <br>
    {% comment %} < class="control">
    <input class="input" type="text" placeholder="Título"> 
    {{form.title}} {% endcomment %}
 
                 {% comment %} <div class="form-group">  <b> Título: </b>  {{form.title}} </div>
                 <div class="form-group">  <b> Descrição: </b>  {{form.description}} </div>
                 <div class="form-group">  <b> Tipo: </b>  {{form.tipo}} </div>
                 <div class="custom-control"> </b> Status da Tarefa: </b>  {{form.complete}} </div>
                 <input type="checkbox" name="msg" id="mail30" class="mail-choice"> {% endcomment %}

{{form|crispy}}

                <input type="submit" value="Salvar" class="add-button" name="action">          

    </form>
</div></div></div>

     {% endblock content %}

base/templates/base/task_list2.html
{% if request.user.is_authenticated %}
    <p> Ola, {{request.user}} Seja bem vindo. </p>
    <a href ="{% url  'logout' %}" </a>
{% else %}
    <a href="{% url 'login' %}">Entrar no sistema </a>
{% endif %}

<br> <br>

<a href="{% url 'task-create' %}"> Adicionar Tarefa </a>

<form method="GET">
    <input type="text" name="search-area" value="{{searchinput}}">
    <input type="submit" value="procurar">

</form>


<table>
<tr>
    <th> Itens da Lista </th>
    <th>  </th>
    <th> </th>
        
{%for task in tasks%}

<tr> 
    <td> {{task.title}} </td>
    <td> <a href ="{% url 'task' task.id %}"> Visualizar </a> </td>
    <td> <a href ="{% url 'task-update' task.id %}"> Editar </a> </td>
    <td> <a href ="{% url 'task-delete' task.id %}"> Deletar </a> </td>


    </tr>
    {% empty %}
    <h3>  Não há itens na lista </h3>
    {% endfor %}

</table>

<br> <br>  <br>
    <a href="{% url 'logout' %}"> Sair do Sistema </a>